// Generated by https://quicktype.io
export interface LoginData {
    correo:   string;
    password: string;
}

export interface RegisterData {
    correo:   string;
    password: string;
    nombre:   string;
}


export interface LoginResponse {
    usuario: Usuario;
    token:   string;
}

export interface Usuario {
    rol:    string;
    estado: boolean;
    google: boolean;
    nombre: string;
    correo: string;
    uid:    string;
    img?:   string;
}


//productos 
// Generated by https://quicktype.io

export interface ProductsResponse {
    total:     number;
    productos: Producto[];
}

export interface Producto {
    precio:    number;
    _id:       string;
    nombre:    string;
    categoria: Categoria;
    usuario:   Categoria;
    img?:      string;
}

export interface Categoria {
    _id:    ID;
    nombre: Nombre;
}

export enum ID {
    The63A469D9C73Aaa365Cec5Df0 = "63a469d9c73aaa365cec5df0",
    The63A46B08C73Aaa365Cec5Df5 = "63a46b08c73aaa365cec5df5",
    The63Aa35D210414F27B44F0A5F = "63aa35d210414f27b44f0a5f",
}

export enum Nombre {
    Controles = "CONTROLES",
    Mensualidad = "MENSUALIDAD ",
    Test1 = "test 1",
}
